# Generated by Django 5.2.4 on 2025-11-03 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0007_anime_age_rating_anime_alternative_titles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1.0, 1.0), (1.1, 1.1), (1.2, 1.2), (1.3, 1.3), (1.4, 1.4), (1.5, 1.5), (1.6, 1.6), (1.7, 1.7), (1.8, 1.8), (1.9, 1.9), (2.0, 2.0), (2.1, 2.1), (2.2, 2.2), (2.3, 2.3), (2.4, 2.4), (2.5, 2.5), (2.6, 2.6), (2.7, 2.7), (2.8, 2.8), (2.9, 2.9), (3.0, 3.0), (3.1, 3.1), (3.2, 3.2), (3.3, 3.3), (3.4, 3.4), (3.5, 3.5), (3.6, 3.6), (3.7, 3.7), (3.8, 3.8), (3.9, 3.9), (4.0, 4.0), (4.1, 4.1), (4.2, 4.2), (4.3, 4.3), (4.4, 4.4), (4.5, 4.5), (4.6, 4.6), (4.7, 4.7), (4.8, 4.8), (4.9, 4.9), (5.0, 5.0), (5.1, 5.1), (5.2, 5.2), (5.3, 5.3), (5.4, 5.4), (5.5, 5.5), (5.6, 5.6), (5.7, 5.7), (5.8, 5.8), (5.9, 5.9), (6.0, 6.0), (6.1, 6.1), (6.2, 6.2), (6.3, 6.3), (6.4, 6.4), (6.5, 6.5), (6.6, 6.6), (6.7, 6.7), (6.8, 6.8), (6.9, 6.9), (7.0, 7.0), (7.1, 7.1), (7.2, 7.2), (7.3, 7.3), (7.4, 7.4), (7.5, 7.5), (7.6, 7.6), (7.7, 7.7), (7.8, 7.8), (7.9, 7.9), (8.0, 8.0), (8.1, 8.1), (8.2, 8.2), (8.3, 8.3), (8.4, 8.4), (8.5, 8.5), (8.6, 8.6), (8.7, 8.7), (8.8, 8.8), (8.9, 8.9), (9.0, 9.0), (9.1, 9.1), (9.2, 9.2), (9.3, 9.3), (9.4, 9.4), (9.5, 9.5), (9.6, 9.6), (9.7, 9.7), (9.8, 9.8), (9.9, 9.9), (10.0, 10.0)], decimal_places=1, default=5.0, max_digits=3)),
                ('review_text', models.TextField(blank=True, null=True, verbose_name='Review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anime Review',
                'verbose_name_plural': 'Anime Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
