# Generated by Django 5.2.4 on 2025-08-03 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='anime_posters/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='anime_banners/')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('shounen', 'Shounen'), ('seinen', 'Seinen'), ('shoujo', 'Shoujo'), ('fantasy', 'Fantasy'), ('mecha', 'Mecha'), ('horror', 'Horror'), ('romance', 'Romance'), ('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama')], max_length=20)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('upcoming', 'Upcoming'), ('hiatus', 'On Hiatus')], default='ongoing', max_length=20)),
                ('total_episodes', models.IntegerField(default=0)),
                ('current_episode', models.IntegerField(default=0)),
                ('release_year', models.IntegerField()),
                ('studio', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('timeline_position', models.IntegerField(default=0, help_text='Position in timeline (2000-2025)')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('character_image', models.ImageField(blank=True, null=True, upload_to='characters/')),
                ('is_main_character', models.BooleanField(default=False)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='anime.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('air_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.anime')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('anime', 'episode_number')},
            },
        ),
    ]
