# Generated by Django 5.2.4 on 2025-08-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='banner_url',
            field=models.URLField(blank=True, help_text='Or enter banner image URL', null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='poster_url',
            field=models.URLField(blank=True, help_text='Or enter poster image URL', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='character_image_url',
            field=models.URLField(blank=True, help_text='Or enter character image URL', null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Upload banner from your computer', null=True, upload_to='anime_banners/'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Upload poster from your computer', null=True, upload_to='anime_posters/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_image',
            field=models.ImageField(blank=True, help_text='Upload character image from computer', null=True, upload_to='characters/'),
        ),
    ]
