# Generated by Django 5.2.4 on 2025-08-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_banner_url_anime_poster_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL for anime video/preview', null=True),
        ),
    ]
