# Generated by Django 5.2.4 on 2025-08-04 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_remove_anime_age_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='age_rating',
            field=models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance'), ('PG13', 'PG-13'), ('R', 'Restricted'), ('NC17', 'Adults Only')], default='PG13', max_length=10),
        ),
        migrations.AddField(
            model_name='anime',
            name='alternative_titles',
            field=models.TextField(blank=True, help_text='Alternative titles separated by commas', null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='anilist_url',
            field=models.URLField(blank=True, help_text='AniList page URL', null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='content_warnings',
            field=models.TextField(blank=True, help_text='Content warnings separated by commas', null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='end_date',
            field=models.DateField(blank=True, help_text='Last episode air date', null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='ending_theme_url',
            field=models.URLField(blank=True, help_text='Ending theme video URL', null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='episode_duration',
            field=models.IntegerField(default=24, help_text='Average episode duration in minutes'),
        ),
        migrations.AddField(
            model_name='anime',
            name='episodes_per_season',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='anime',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_award_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_completed_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_editor_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_trending',
            field=models.BooleanField(default=False, help_text='Show in trending section'),
        ),
        migrations.AddField(
            model_name='anime',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Anime logo/title image', null=True, upload_to='anime_logos/'),
        ),
        migrations.AddField(
            model_name='anime',
            name='mal_score',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='MyAnimeList score', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='music_composer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='myanimelist_url',
            field=models.URLField(blank=True, help_text='MyAnimeList page URL', null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='next_episode_date',
            field=models.DateField(blank=True, help_text='Next episode air date', null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='official_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='opening_theme_url',
            field=models.URLField(blank=True, help_text='Opening theme video URL', null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='popularity_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='producer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='screenshot1',
            field=models.ImageField(blank=True, null=True, upload_to='anime_screenshots/'),
        ),
        migrations.AddField(
            model_name='anime',
            name='screenshot2',
            field=models.ImageField(blank=True, null=True, upload_to='anime_screenshots/'),
        ),
        migrations.AddField(
            model_name='anime',
            name='screenshot3',
            field=models.ImageField(blank=True, null=True, upload_to='anime_screenshots/'),
        ),
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.CharField(blank=True, choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='secondary_genres',
            field=models.CharField(blank=True, help_text='Additional genres separated by commas', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for cards and previews', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='source',
            field=models.CharField(choices=[('manga', 'Manga'), ('light_novel', 'Light Novel'), ('visual_novel', 'Visual Novel'), ('game', 'Video Game'), ('original', 'Original'), ('web_manga', 'Web Manga'), ('novel', 'Novel'), ('other', 'Other')], default='manga', max_length=20),
        ),
        migrations.AddField(
            model_name='anime',
            name='start_date',
            field=models.DateField(blank=True, help_text='First episode air date', null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=models.TextField(blank=True, help_text='Search tags separated by commas', null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='total_seasons',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='anime',
            name='trending_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='user_ratings_count',
            field=models.IntegerField(default=0, help_text='Number of user ratings'),
        ),
        migrations.AddField(
            model_name='anime',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.CharField(choices=[('shounen', 'Shounen'), ('seinen', 'Seinen'), ('shoujo', 'Shoujo'), ('fantasy', 'Fantasy'), ('mecha', 'Mecha'), ('horror', 'Horror'), ('romance', 'Romance'), ('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('slice_of_life', 'Slice of Life'), ('supernatural', 'Supernatural'), ('thriller', 'Thriller'), ('mystery', 'Mystery'), ('sports', 'Sports'), ('music', 'Music'), ('school', 'School')], max_length=20),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('upcoming', 'Upcoming'), ('hiatus', 'On Hiatus'), ('cancelled', 'Cancelled')], default='ongoing', max_length=20),
        ),
    ]
